name = "Dungeons and Mineshafts"
author = "Ben Murray, Lyle Bicking"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "067519fe6bdd85a070b3ae50890ad437a24aa97fada5e77d8acc4c0cd840c4b5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
