name = "Dungeons and Mineshafts"
author = "Ben Murray, Lyle Bicking"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "761ac0e02f6bdeff528304d4fef7d6f35394010e9009fd7879c2d3d919add807"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
