name = "Dungeons and Mineshafts"
author = "Ben Murray, Lyle Bicking"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8662bfb3188a8891fb192b5da6f0dc5f60d5fd4ddbffe3f2a7fb2b7165c3c56c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
