# .github/workflows/release.yml
name: Create release

on:
  push:
    # only run when you push a tag like "v1.2.3"
    tags:
      - 'v*'

permissions:
  contents: write   # allow creating releases & uploading assets

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Generate mod list
        run: packwiz list > mods.txt

      - name: Package packwiz directory
        run: zip -r packwiz.zip packwiz

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          gh release create "$TAG" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "${TAG#v}" \
            --notes-file mods.txt \
            --assets packwiz.zip
